services:
  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
  consumer:
    build: ./consumer-py
    depends_on:
      rabbitmq:
        condition: service_started
  producer:
    build: ./producer
    depends_on:
      rabbitmq:
        condition: service_started
      consumer:
        condition: service_started
