services:
  redis:
    image: "redis/redis-stack-server:latest"
  set:
    depends_on:
      redis:
        condition: service_started
    build: ./set
    environment:
      - REDIS_URL=redis://redis:6379/0
    healthcheck:
      test: "exit 0"
  get:
    depends_on:
      redis:
        condition: service_started
    build: ./get
    environment:
      - REDIS_URL=redis://redis:6379/0
