services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  consumer:
    build: ./consumer-py
    depends_on:
      kafka:
        condition: service_started
    environment:
      - KAFKA_HOST=kafka:9092
  producer:
    build: ./producer
    depends_on:
      kafka:
        condition: service_started
    depends_on:
      consumer:
        condition: service_started
    environment:
      - KAFKA_HOST=kafka:9092
